accounts/urls.py
from django.urls import path
from .views import login, logout, signup

app_name = 'accounts'
urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('signup/', signup, name='signup'),
]

main/urls.py
# main의 urls.py 작성
from django.urls import path
from django.contrib import admin
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.mainpage, name='mainpage'),
    path('product/<int:product_id>/', views.product_detail, name="product_detail"),
    path('product/<int:product_id>/create_comment/', views.create_comment, name="create_comment"),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name="delete_comment"),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='main'),
    path('accounts/', include('accounts.urls'), name='accounts'),
]

accounts/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    id                =   models.AutoField(primary_key=True)
    name              =   models.CharField(max_length=50)
    description       =   models.CharField(max_length=50)
    origin_price      =   models.IntegerField()
    discount_price    =   models.IntegerField()
    discount_rate     =   models.IntegerField()
    category          =   models.ManyToManyField('Category')
    notice            =   models.CharField(max_length=200)
    image_url         =   models.URLField(max_length=2000)

    def summary(self):
        return self.description[:20]
    
    def __str__(self):
        return self.name
    
    class Meta:
        db_table    = 'products'

class Category(models.Model):
    name            =   models.CharField(max_length=45)

    def __str__(self):
        return self.name
    class Meta:
        db_table    = 'categories'

class ProductComment(models.Model):
    id              = models.AutoField(primary_key=True)
    user            = models.ForeignKey(User, on_delete=models.CASCADE)
    product         = models.ForeignKey('Product', on_delete=models.CASCADE)
    star            = models.IntegerField()
    content         = models.TextField()
    created_at      = models.DateTimeField(auto_now=True)

    class Meta:
        db_table    = 'product_comments'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import auth
from django.contrib.auth.models import User

# Create your views here.
def login_page(request):
    return render(request, 'accounts/login.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('main:mainpage')
        else:
            return render(request, 'accounts/login.html', {'error': '아이디나 비밀번호가 틀렸습니다. 다시 입력해주세요.'})
    else:
        return render(request, 'accounts/login.html', {'error': '로그인 실패'})
    

def logout(request):
    auth.logout(request)
    return redirect('main:mainpage')

def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        password2 = request.POST['password2']

        # username 미입력시 에러
        if not username:
            return render(request, 'accounts/signup.html', {'error': '닉네임을 입력해주세요.'})
        
        # 비밀번호에 영문 대소문자, 숫자, 특수문자 (@ ! ? - _)가 각각 1개 이상 포함되어야 하며 8자 이상이어야 함
        if not (any(c.isupper() for c in password) and any(c.islower() for c in password) and any(c.isdigit() for c in password) and any(c in '@!?-_' for c in password) and len(password) >= 8):
            return render(request, 'accounts/signup.html', {'error': '비밀번호가 조건에 맞지 않습니다. 다시 입력해주세요.'})

        if password == password2:
            if User.objects.filter(username=username).exists():
                return render(request, 'accounts/signup.html', {'error': '이미 사용중인 닉네임입니다.'})
            else:
                user = User.objects.create_user(username=username, password=password)
                auth.login(request, user)
                return redirect('main:mainpage')
        else:
            return render(request, 'accounts/signup.html', {'error': '비밀번호가 일치하지 않습니다.'})
    else:
        return render(request, 'accounts/signup.html')

main/views.py
from django.shortcuts import render, redirect
from .models import Product, ProductComment

# Create your views here.
# 메인페이지와 메인페이지의 products 정보들을 불러오는 함수
def mainpage(request):
    products = Product.objects.all()
    return render(request, 'main/mainpage.html', {'products': products})

# 상품의 상세페이지를 불러오는 함수
def product_detail(request, product_id):
    product = Product.objects.get(id=product_id)
    comments = product.productcomment_set.all()
    return render(request, 'main/product_detail_page.html', {'product': product, 'comments': comments})

# 상품의 상세페이지에서 댓글을 작성하는 함수
def create_comment(request, product_id):
    product = Product.objects.get(id=product_id)
    if request.method == 'POST':
        star = request.POST['star']
        content = request.POST['content']
        product.productcomment_set.create(star=star, content=content, user_id=request.user.id)
    return redirect('main:product_detail', product_id)

# 상품의 상세페이지에서 댓글을 삭제하는 함수 (단, 댓글 작성자만 삭제 가능)
def delete_comment(request, comment_id):
    comment = ProductComment.objects.get(id=comment_id)
    product = comment.product
    if request.user.id != comment.user_id:
        comments = product.productcomment_set.all()
        return render(request, 'main/product_detail_page.html', {'product': product, 'comments': comments, 'error': '본인의 댓글만 삭제할 수 있습니다.'})
    comment.delete()
    return redirect('main:product_detail', product.id)

accounts/templates/accounts/login.html
{% extends 'base.html' %} {% block content %} {% load static %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/accounts/signup.css'%}"
/>

<div class="screen">
  <div class="container">
    <form action="{% url 'accounts:login' %}" method="post" class="Frame">
      {% csrf_token %}
      <div class="Pretendard Title">로그인</div>
      <div class="Pretendard bold shell" id="id_box">
        <input
          type="text"
          name="username"
          id="id"
          class="Pretendard gray input_box"
          placeholder="아이디를 입력해주세요."
          onkeyup="validateForm()"
        />
        <div id="id-feedback" class="Pretendard gray small"></div>
      </div>
      <div class="Pretendard bold shell" id="password_box">
        <div>
          <input
            type="password"
            name="password"
            id="password"
            class="Pretendard gray input_box"
            placeholder="비밀번호를 입력해주세요."
            onkeyup="validateForm()"
          />
        </div>
      </div>
      <div class="Pretendard shell" style="align-self: flex-end; margin-right: 3.5em; margin-bottom: 1em;">
        <span>아이디 찾기</span><span style="margin-left: 1em; margin-right: 1em;">|</span><span>비밀번호 찾기</span>
      </div>
      <button
        disabled
        type="submit"
        class="Pretendard middle button button-inactive"
        id="submit"
      >
        로그인
      </button>
      <button class="Pretendard middle button" id="otherpage">회원가입</button>
    </form>
  </div>
</div>

{% if error %}
<div style="color: red">{{ error }}</div>
{% endif %}

<script>
  function validateForm() {
    const id = document.querySelector("#id");
    const password = document.querySelector("#password");
    const button = document.querySelector("#submit");

    function validateId() {
      return id.value.trim() !== "";
    }

    function validatePassword() {
      return password.value.trim() !== "";
    }

    // 모든 조건이 충족되면 버튼 활성화
    if (
      validateId() &&
      validatePassword(password.value)
    ) {
      button.disabled = false;
      button.classList.remove("button-inactive");
      button.classList.add("button-active");
    } else {
      button.disabled = true;
      button.classList.remove("button-active");
      button.classList.add("button-inactive");
    }
  }
</script>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %} {% block content %} {% load static %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/accounts/signup.css'%}"
/>

<div class="screen">
  <div class="container">
    <form action="{% url 'accounts:signup' %}" method="post" class="Frame">
      {% csrf_token %}
      <div class="Pretendard Title">회원가입</div>
      <hr style="width: 640px; height: 1px; border: none; background: #000" />
      <div class="Pretendard bold shell" id="id_box">
        <label for="id" class="box"> 아이디 </label>
        <input
          type="text"
          name="username"
          id="id"
          class="Pretendard gray input_box"
          placeholder="아이디를 입력해주세요."
          onkeyup="validateForm()"
        />
        <div id="id-feedback" class="Pretendard gray small"></div>
      </div>
      <div class="Pretendard bold shell" id="password_box">
        <label for="password" class="box"> 비밀번호 </label>
        <div>
          <input
            type="password"
            name="password"
            id="password"
            class="Pretendard gray input_box"
            placeholder="비밀번호를 입력해주세요."
          />
          <div id="password-feedback" class="Pretendard gray small">
            <p>* 비밀번호를 8자 이상으로 작성해주세요.</p>
            <p>* 영문 대소문자, 숫자, 특수문자를 하나 이상 포함해주세요.</p>
            <p>* 사용가능 특수문자 @!?-_</p>
          </div>
        </div>
      </div>
      <div>
        <div class="Pretendard bold shell" id="check_password_box">
          <label for="check_password" class="box"> 비밀번호 확인 </label>
          <input
            type="password"
            name="password2"
            id="check_password"
            class="Pretendard gray input_box"
            placeholder="비밀번호를 한 번 더 입력해주세요."
            onkeyup="validateForm()"
          />
        </div>
        <div id="check-password-feedback" class="Pretendard gray small"></div>
      </div>
      <hr
        style="width: 640px; height: 1px; border: none; background: #e2e2e2"
      />
      <button disabled type="submit" class="Pretendard middle button button-inactive" id="submit">
        가입하기
      </button>
    </form>
  </div>
</div>

{% if error %}
<div style="color: red">{{ error }}</div>
{% endif %}

<script>
  function validateForm() {
    const id = document.querySelector("#id");
    const password = document.querySelector("#password");
    const check_password = document.querySelector("#check_password");
    const button = document.querySelector("#submit");
    const checkPasswordFeedback = document.querySelector("#check-password-feedback");

    function validateId() {
      return id.value.trim() !== "";
    }

    function validatePassword(password) {
      const minLength = 8;
      const hasUpperCase = /[A-Z]/.test(password);
      const hasLowerCase = /[a-z]/.test(password);
      const hasSpecialChar = /[@!?-_]/.test(password);

      return (
        password.length >= minLength &&
        hasUpperCase &&
        hasLowerCase &&
        hasSpecialChar
      );
    }

    function validatePasswordCheck(password, check_password) {
      return password === check_password;
    }

    // 비밀번호 확인 검사
    if (!validatePasswordCheck(password.value, check_password.value)) {
      checkPasswordFeedback.textContent = "비밀번호가 일치하지 않습니다.";
      checkPasswordFeedback.style.color = "red";
    } else {
      checkPasswordFeedback.textContent = "";
    }

    // 모든 조건이 충족되면 버튼 활성화
    if (
      validateId() &&
      validatePassword(password.value) &&
      validatePasswordCheck(password.value, check_password.value)
    ) {
      button.disabled = false;
      button.classList.remove("button-inactive");
      button.classList.add("button-active");
    } else {
      button.disabled = true;
      button.classList.remove("button-active");
      button.classList.add("button-inactive");
    }
  }
</script>
{% endblock %}

main/templates/main/mainpage.html
{% extends 'base.html' %} {% block content %} {% load static %}
<!-- css 파일 -->
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/main/main_page.css'%}"
/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css" />


<div class="tagFrame">
  <div class="tag">
    <ul class="tagList">
      <li class="tagTextBox"><a class="tagText">인기신상랭킹</a></li>
      <li class="tagTextBox"><a class="tagText">입점특가</a></li>
      <li class="tagTextBox"><a class="tagText">간편한끼</a></li>
      <li class="tagTextBox"><a class="tagText">요즘간식</a></li>
      <li class="tagTextBox"><a class="tagText">주방·리빙</a></li>
      <li class="tagTextBox"><a class="tagText">뷰티</a></li>
      <li class="tagTextBox"><a class="tagText">패션·잡화</a></li>
    </ul>
  </div>
</div>

<div class="bodyFrame">
  <div class="filterFrame">
    <div class="filterBox">
      <span class="filterText H3">필터</span>
      <button class="refreshIcon">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" style="fill: #DDD; width: 20px; height: 20px;">
          <path d="M9.825 20.7001C8.10833 20.2167 6.70833 19.2709 5.625 17.8625C4.54167 16.4542 4 14.8334 4 13C4 12.05 4.15833 11.1459 4.475 10.2875C4.79167 9.42922 5.24167 8.64172 5.825 7.92505C6.00833 7.72505 6.23333 7.62088 6.5 7.61255C6.76667 7.60422 7.00833 7.70838 7.225 7.92505C7.40833 8.10838 7.50417 8.33338 7.5125 8.60005C7.52083 8.86672 7.43333 9.11672 7.25 9.35005C6.85 9.86672 6.54167 10.4334 6.325 11.05C6.10833 11.6667 6 12.3167 6 13C6 14.35 6.39583 15.5542 7.1875 16.6125C7.97917 17.6709 9 18.3917 10.25 18.7751C10.4667 18.8417 10.6458 18.9667 10.7875 19.1501C10.9292 19.3334 11 19.5334 11 19.75C11 20.0834 10.8833 20.3459 10.65 20.5375C10.4167 20.7292 10.1417 20.7834 9.825 20.7001ZM14.175 20.7001C13.8583 20.7834 13.5833 20.725 13.35 20.5251C13.1167 20.3251 13 20.0584 13 19.725C13 19.5251 13.0708 19.3334 13.2125 19.1501C13.3542 18.9667 13.5333 18.8417 13.75 18.7751C15 18.3751 16.0208 17.6501 16.8125 16.6C17.6042 15.55 18 14.35 18 13C18 11.3334 17.4167 9.91672 16.25 8.75005C15.0833 7.58338 13.6667 7.00005 12 7.00005H11.925L12.325 7.40005C12.5083 7.58338 12.6 7.81672 12.6 8.10005C12.6 8.38338 12.5083 8.61672 12.325 8.80005C12.1417 8.98338 11.9083 9.07505 11.625 9.07505C11.3417 9.07505 11.1083 8.98338 10.925 8.80005L8.825 6.70005C8.725 6.60005 8.65417 6.49172 8.6125 6.37505C8.57083 6.25838 8.55 6.13338 8.55 6.00005C8.55 5.86672 8.57083 5.74172 8.6125 5.62505C8.65417 5.50838 8.725 5.40005 8.825 5.30005L10.925 3.20005C11.1083 3.01672 11.3417 2.92505 11.625 2.92505C11.9083 2.92505 12.1417 3.01672 12.325 3.20005C12.5083 3.38338 12.6 3.61672 12.6 3.90005C12.6 4.18338 12.5083 4.41672 12.325 4.60005L11.925 5.00005H12C14.2333 5.00005 16.125 5.77505 17.675 7.32505C19.225 8.87505 20 10.7667 20 13C20 14.8167 19.4583 16.4334 18.375 17.85C17.2917 19.2667 15.8917 20.2167 14.175 20.7001Z" fill="#DDD"/>
        </svg>
        <span class="refreshText H3">초기화</span>
      </button>  
    </div>
    <div class="categoryFrame">
      <button class="categoryHeader">
        <div class="categoryHeaderText H3">카테고리</div>
        <svg class="categoryIcon" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20" fill="none">
          <path d="M9.98572 9.13897L6.44405 12.6806C6.30988 12.8148 6.14787 12.8796 5.95801 12.875C5.76815 12.8704 5.60613 12.801 5.47197 12.6667C5.33766 12.5324 5.27051 12.368 5.27051 12.1736C5.27051 11.9791 5.33766 11.8148 5.47197 11.6806L9.49967 7.65273C9.5737 7.5787 9.65009 7.52661 9.72884 7.49648C9.80759 7.46648 9.89322 7.45147 9.98572 7.45147C10.0784 7.45147 10.164 7.46648 10.2428 7.49648C10.3214 7.52661 10.3978 7.5787 10.472 7.65273L14.5136 11.6944C14.6478 11.8287 14.7126 11.9908 14.708 12.1806C14.7034 12.3704 14.634 12.5324 14.4997 12.6667C14.3654 12.801 14.201 12.8681 14.0065 12.8681C13.8121 12.8681 13.6478 12.801 13.5136 12.6667L9.98572 9.13897Z" fill="#999999"/>
          </svg>
      </button>
        <div class="sideBarNavFrame">
            <div class="sidebarNav">
              <label for="nav1">
                <input type="checkbox" name="group" id="nav1" />
                <span class="custom-checkbox"></span>
              </label>
              <span class="categoryNavText">스킨케어·메이크업</span>
              <span class="categoryNavNum">68</span>
            </div>
            <div class="sidebarNav">
              <label for="nav2">
                <input type="checkbox" name="group" id="nav2" />
                <span class="custom-checkbox"></span>
              </label>
              <span class="categoryNavText">럭셔리뷰티</span>
              <span class="categoryNavNum">24</span>
            </div>
            <div class="sidebarNav">
              <label for="nav3">
                <input type="checkbox" name="group" id="nav3" />
                <span class="custom-checkbox"></span>
              </label>
              <span class="categoryNavText">간식·과자·떡</span>
              <span class="categoryNavNum">28</span>
            </div>
          
        </div>
    </div>


  </div>

  <div class="bodyBox">
    <div class="sortingBar">
      <span class="totalNum H3">총 120건</span>
      <div class="sortingMenu">
        <span class="sortingMenuText H3" id="c">추천순</span>
        <span class="sortingMenuLine"></span>
        <span class="sortingMenuText H3">신상품순</span>
        <span class="sortingMenuLine"></span>
        <span class="sortingMenuText H3">판매량순</span>
        <span class="sortingMenuLine"></span>
        <span class="sortingMenuText H3">혜택순</span>
        <span class="sortingMenuLine"></span>
        <span class="sortingMenuText H3">낮은 가격순</span>
        <span class="sortingMenuLine"></span>
        <span class="sortingMenuText H3">높은 가격순</span>
    </div>
  </div>
  <div class="categoryChoiceBox">
    <button class="xButton">
      <span class="xButtonText">스킨케어·메이크업</span>
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20" fill="none">
        <path d="M9.99967 11.1668L5.91634 15.2502C5.76356 15.4029 5.56912 15.4793 5.33301 15.4793C5.0969 15.4793 4.90245 15.4029 4.74967 15.2502C4.5969 15.0974 4.52051 14.9029 4.52051 14.6668C4.52051 14.4307 4.5969 14.2363 4.74967 14.0835L8.83301 10.0002L4.74967 5.91683C4.5969 5.76405 4.52051 5.56961 4.52051 5.3335C4.52051 5.09738 4.5969 4.90294 4.74967 4.75016C4.90245 4.59738 5.0969 4.521 5.33301 4.521C5.56912 4.521 5.76356 4.59738 5.91634 4.75016L9.99967 8.8335L14.083 4.75016C14.2358 4.59738 14.4302 4.521 14.6663 4.521C14.9025 4.521 15.0969 4.59738 15.2497 4.75016C15.4025 4.90294 15.4788 5.09738 15.4788 5.3335C15.4788 5.56961 15.4025 5.76405 15.2497 5.91683L11.1663 10.0002L15.2497 14.0835C15.4025 14.2363 15.4788 14.4307 15.4788 14.6668C15.4788 14.9029 15.4025 15.0974 15.2497 15.2502C15.0969 15.4029 14.9025 15.4793 14.6663 15.4793C14.4302 15.4793 14.2358 15.4029 14.083 15.2502L9.99967 11.1668Z" fill="#DDDDDD"/>
        </svg>
    </button>  
  </div>
  <div class="itemList">
    {% for product in products %}
    <div class="cardFrame">
      <a href="product/{{product.id}}">
        <img src="{{product.image_url}}" style="width: 249px; height: 320px;" />
      </a>
      <div class="cartBox">
        <button class="cartIcon">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
            <path d="M7.5 22C6.95 22 6.47917 21.8042 6.0875 21.4125C5.69583 21.0208 5.5 20.55 5.5 20C5.5 19.45 5.69583 18.9792 6.0875 18.5875C6.47917 18.1958 6.95 18 7.5 18C8.05 18 8.52083 18.1958 8.9125 18.5875C9.30417 18.9792 9.5 19.45 9.5 20C9.5 20.55 9.30417 21.0208 8.9125 21.4125C8.52083 21.8042 8.05 22 7.5 22ZM17.5 22C16.95 22 16.4792 21.8042 16.0875 21.4125C15.6958 21.0208 15.5 20.55 15.5 20C15.5 19.45 15.6958 18.9792 16.0875 18.5875C16.4792 18.1958 16.95 18 17.5 18C18.05 18 18.5208 18.1958 18.9125 18.5875C19.3042 18.9792 19.5 19.45 19.5 20C19.5 20.55 19.3042 21.0208 18.9125 21.4125C18.5208 21.8042 18.05 22 17.5 22ZM6.65 6L9.05 11H16.05L18.8 6H6.65ZM5.7 4H20.45C20.8333 4 21.125 4.17083 21.325 4.5125C21.525 4.85417 21.5333 5.2 21.35 5.55L17.8 11.95C17.6167 12.2833 17.3708 12.5417 17.0625 12.725C16.7542 12.9083 16.4167 13 16.05 13H8.6L7.5 15H18.5C18.7833 15 19.0208 15.0958 19.2125 15.2875C19.4042 15.4792 19.5 15.7167 19.5 16C19.5 16.2833 19.4042 16.5208 19.2125 16.7125C19.0208 16.9042 18.7833 17 18.5 17H7.5C6.75 17 6.18333 16.6708 5.8 16.0125C5.41667 15.3542 5.4 14.7 5.75 14.05L7.1 11.6L3.5 4H2.5C2.21667 4 1.97917 3.90417 1.7875 3.7125C1.59583 3.52083 1.5 3.28333 1.5 3C1.5 2.71667 1.59583 2.47917 1.7875 2.2875C1.97917 2.09583 2.21667 2 2.5 2H4.125C4.30833 2 4.48333 2.05 4.65 2.15C4.81667 2.25 4.94167 2.39167 5.025 2.575L5.7 4Z" fill="#333333"/>
            </svg>
            <span class="cartText">담기</span>
        </button>
      </div>
      <div class="productFrame">
        <a id="link" href="product/{{product.id}}">
        <div class="ex1">샛별배송</div>
        <div class="productName"><span class="name">{{product}}</span></div>
        <div class="productDescription"><span class="des">{{product.description}}</span></div>
        <div class="priceFrame">
          <p class="originPrice">{{product.origin_price}}원</p>
        </div>
        <div class="discountFrame">
          <span class="rate">{{product.discount_rate}}%</span>
          <span class="discountPrice">{{product.discount_price}}원</span>
        </div>
        </a>
      </div>
    </div>
    {% endfor %}
  </div>
</div>


<!-- js 파일 -->
<script src="{% static 'js/main/main_page.js'%}"></script>

{% endblock %}

main/templates/main/product_detail_page.html
{% extends 'base.html' %} {% block content %} {% load static %}
<link

  rel="stylesheet"
  type="text/css"
  href="{% static 'css/main/product_detail_page.css'%}"
/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css" />

<!-- 코드 작성시, 아래 부분(endblock 이전)은 전체 삭제하고 작성하세요 -->

<!----------------tip!---------------->
<!-- 상품 데이터베이스는 프로젝트에 넣어뒀어요 -->
<!-- 아래와 같은 형식으로 사용하세요 -->

<!-- 데이터 사용 예시 
<img src="{{product.image_url}}" style="width: 100px" />
<p>{{product.name}}</p>
<p>{{product.discount_rate}}%</p>
<p>{{product.discount_price}} 원</p>
<p>{{product.notice}}</p>
데이터 사용 예시 -->

<div class="bodyScreen">
  <div class="bodyContentFrame">
    <div class="bodyImage">
      <img class="bodyImage" src="{{product.image_url}}" />
    </div>
    <div class="bodyContent">
      <div class="contentFrame1">

        <span class="text1">샛별배송</span>

        <div class="nameFrame">
          <span class="pName">{{product.name}}</span>
        </div>

        <div class="priceFrame">
          <span class="rate">{{product.discount_rate}}%</span> 
          <span class="price">{{product.discount_price}} 원</span>
        </div>

        <div class="line6"> </div>

        <div class="noticeFrame">
          <span class="noticetext1">안내사항</span>
          <span class="notice">{{product.notice}}</span>
        </div>

        <div class="line6"> </div>

        <div class="choiceFrame">
          <span class="choiceText">상품선택</span>
          <div class="choicebuttonFrame">
            <span class="prductName">{{product.name}}</span>
            <div class="calculate">
              <span class="m">-</span>
              <span class="num">2</span>
              <span class="p">+</span>
            </div>
          </div>
        </div>
        <div class="line6"> </div>
  </div>
        <div class="navFrame">
          <div class="totalPriceFrame">
            <div class="totalPrice">
              <span class="priceExText">총 상품 금액 :</span>
              <span class="price">100000 원</span>
            </div>
          </div>
            <button class="loginButton"><span class="login">로그인</span></button>
          
        </div>
      
    </div>
  </div>
  
</div>


<script src="{% static 'js/main/product_detail_page.js'%}"></script>
{% endblock %}

project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>컬리 - 마켓컬리/뷰티컬리</title>

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/base/reset.css'%}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/base/style.css'%}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/base/font.css'%}"
    />
  </head>
  <body>
    <!-- 상단 네브바 -->
    {% include 'shared/_topnav.html' %}
    <!-- 상단 네브바 -->

    <!-- 내용 -->
    {% block content %} {% endblock %}
    <!-- 내용 -->
  </body>
</html>